// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
  urlSearchParamsBodySerializer,
} from "@hey-api/client-axios";
import type {
  AuthJwtLoginData,
  AuthJwtLoginError,
  AuthJwtLoginResponse,
  AuthJwtLogoutError,
  AuthJwtLogoutResponse,
  RegisterRegisterData,
  RegisterRegisterError,
  RegisterRegisterResponse,
  ResetForgotPasswordData,
  ResetForgotPasswordError,
  ResetForgotPasswordResponse,
  ResetResetPasswordData,
  ResetResetPasswordError,
  ResetResetPasswordResponse,
  VerifyRequestTokenData,
  VerifyRequestTokenError,
  VerifyRequestTokenResponse,
  VerifyVerifyData,
  VerifyVerifyError,
  VerifyVerifyResponse,
  UsersCurrentUserError,
  UsersCurrentUserResponse,
  UsersPatchCurrentUserData,
  UsersPatchCurrentUserError,
  UsersPatchCurrentUserResponse,
  UsersUserData,
  UsersUserError,
  UsersUserResponse,
  UsersPatchUserData,
  UsersPatchUserError,
  UsersPatchUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserError,
  UsersDeleteUserResponse,
  ReadItemData,
  ReadItemError,
  ReadItemResponse,
  CreateItemData,
  CreateItemError,
  CreateItemResponse,
  DeleteItemData,
  DeleteItemError,
  DeleteItemResponse,
  SyncGmailMessagesData,
  SyncGmailMessagesError,
  SyncGmailMessagesResponse,
  GetGmailConnectUrlError,
  GetGmailConnectUrlResponse,
  GetGmailStatusError,
  GetGmailStatusResponse,
  GmailOauthCallbackData,
  GmailOauthCallbackError,
  GmailOauthCallbackResponse,
  TriageGmailWithMcpData,
  TriageGmailWithMcpError,
  TriageGmailWithMcpResponse,
  TriageConnectedGmailData,
  TriageConnectedGmailError,
  TriageConnectedGmailResponse,
  WatchGmailMessagesData,
  WatchGmailMessagesError,
  WatchGmailMessagesResponse,
  GmailWebhookData,
  GmailWebhookError,
  GmailWebhookResponse2,
  SendGmailMessageData,
  SendGmailMessageError,
  SendGmailMessageResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Auth:Jwt.Login
 */
export const authJwtLogin = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AuthJwtLoginData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthJwtLoginResponse,
    AuthJwtLoginError,
    ThrowOnError
  >({
    ...options,
    ...urlSearchParamsBodySerializer,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
    url: "/auth/jwt/login",
  });
};

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogout = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthJwtLogoutResponse,
    AuthJwtLogoutError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/jwt/logout",
  });
};

/**
 * Register:Register
 */
export const registerRegister = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<RegisterRegisterData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RegisterRegisterResponse,
    RegisterRegisterError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/register",
  });
};

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ResetForgotPasswordData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ResetForgotPasswordResponse,
    ResetForgotPasswordError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/forgot-password",
  });
};

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ResetResetPasswordData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ResetResetPasswordResponse,
    ResetResetPasswordError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/reset-password",
  });
};

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<VerifyRequestTokenData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    VerifyRequestTokenResponse,
    VerifyRequestTokenError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/request-verify-token",
  });
};

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<VerifyVerifyData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    VerifyVerifyResponse,
    VerifyVerifyError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/verify",
  });
};

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersCurrentUserResponse,
    UsersCurrentUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/me",
  });
};

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersPatchCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UsersPatchCurrentUserResponse,
    UsersPatchCurrentUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/me",
  });
};

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersUserResponse,
    UsersUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/{id}",
  });
};

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersPatchUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UsersPatchUserResponse,
    UsersPatchUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/{id}",
  });
};

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersDeleteUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    UsersDeleteUserResponse,
    UsersDeleteUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/{id}",
  });
};

/**
 * Read Item
 */
export const readItem = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ReadItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadItemResponse,
    ReadItemError,
    ThrowOnError
  >({
    ...options,
    url: "/items/",
  });
};

/**
 * Create Item
 */
export const createItem = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CreateItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateItemResponse,
    CreateItemError,
    ThrowOnError
  >({
    ...options,
    url: "/items/",
  });
};

/**
 * Delete Item
 */
export const deleteItem = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DeleteItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteItemResponse,
    DeleteItemError,
    ThrowOnError
  >({
    ...options,
    url: "/items/{item_id}",
  });
};

/**
 * Sync Gmail Messages
 */
export const syncGmailMessages = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<SyncGmailMessagesData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SyncGmailMessagesResponse,
    SyncGmailMessagesError,
    ThrowOnError
  >({
    ...options,
    url: "/emails/sync",
  });
};

/**
 * Get Gmail Connect Url
 */
export const getGmailConnectUrl = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetGmailConnectUrlResponse,
    GetGmailConnectUrlError,
    ThrowOnError
  >({
    ...options,
    url: "/emails/gmail/connect-url",
  });
};

/**
 * Get Gmail Status
 */
export const getGmailStatus = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetGmailStatusResponse,
    GetGmailStatusError,
    ThrowOnError
  >({
    ...options,
    url: "/emails/gmail/status",
  });
};

/**
 * Gmail Oauth Callback
 */
export const gmailOauthCallback = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GmailOauthCallbackData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GmailOauthCallbackResponse,
    GmailOauthCallbackError,
    ThrowOnError
  >({
    ...options,
    url: "/emails/gmail/oauth/callback",
  });
};

/**
 * Triage Gmail With Mcp
 */
export const triageGmailWithMcp = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<TriageGmailWithMcpData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    TriageGmailWithMcpResponse,
    TriageGmailWithMcpError,
    ThrowOnError
  >({
    ...options,
    url: "/emails/gmail/triage-mcp",
  });
};

/**
 * Triage Connected Gmail
 */
export const triageConnectedGmail = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<TriageConnectedGmailData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    TriageConnectedGmailResponse,
    TriageConnectedGmailError,
    ThrowOnError
  >({
    ...options,
    url: "/emails/gmail/triage-connected",
  });
};

/**
 * Watch Gmail Messages
 */
export const watchGmailMessages = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<WatchGmailMessagesData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    WatchGmailMessagesResponse,
    WatchGmailMessagesError,
    ThrowOnError
  >({
    ...options,
    url: "/emails/gmail/watch",
  });
};

/**
 * Gmail Webhook
 */
export const gmailWebhook = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GmailWebhookData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    GmailWebhookResponse2,
    GmailWebhookError,
    ThrowOnError
  >({
    ...options,
    url: "/emails/gmail/webhook",
  });
};

/**
 * Send Gmail Message
 */
export const sendGmailMessage = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<SendGmailMessageData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SendGmailMessageResponse,
    SendGmailMessageError,
    ThrowOnError
  >({
    ...options,
    url: "/emails/gmail/send",
  });
};
