// This file is auto-generated by @hey-api/openapi-ts

export type BearerResponse = {
  access_token: string;
  token_type: string;
};

export type Body_auth_reset_forgot_password = {
  email: string;
};

export type Body_auth_reset_reset_password = {
  token: string;
  password: string;
};

export type Body_auth_verify_request_token = {
  email: string;
};

export type Body_auth_verify_verify = {
  token: string;
};

export type ConnectedGmailTriageRequest = {
  /**
   * Gmail search query for the messages OpenAI should triage.
   */
  search_query?: string;
  max_results?: number;
  dry_run?: boolean;
  high_label?: string;
  medium_label?: string;
  low_label?: string;
  user_focus?: string;
};

export type ErrorModel = {
  detail:
    | string
    | {
        [key: string]: string;
      };
};

export type GmailCategory = "primary" | "promotions" | "updates";

export type GmailConnectionStatusResponse = {
  connected: boolean;
  email_address?: string | null;
  categories?: Array<GmailCategory>;
};

export type GmailConnectUrlResponse = {
  url: string;
};

export type GmailMcpTriageRequest = {
  /**
   * Google OAuth access token with Gmail read, modify, and label access.
   */
  google_access_token: string;
  /**
   * Gmail search query for the messages OpenAI should triage.
   */
  search_query?: string;
  max_results?: number;
  /**
   * When true, classify and summarize without applying labels.
   */
  dry_run?: boolean;
  high_label?: string;
  medium_label?: string;
  low_label?: string;
  /**
   * Optional user preference, goals, role, or current focus areas.
   */
  user_focus?: string | null;
};

export type GmailMcpTriageResponse = {
  result: string;
};

export type GmailMessageRead = {
  gmail_id: string;
  thread_id?: string | null;
  category: GmailCategory;
  subject?: string | null;
  sender?: string | null;
  received_at?: string | null;
  snippet?: string | null;
};

export type GmailSendRequest = {
  /**
   * Google OAuth access token with Gmail send access.
   */
  access_token: string;
  to: string;
  subject: string;
  body: string;
  cc?: string | null;
  bcc?: string | null;
};

export type GmailSendResponse = {
  gmail_id: string;
  thread_id?: string | null;
};

export type GmailSyncRequest = {
  /**
   * Google OAuth access token with Gmail read-only access.
   */
  access_token: string;
  categories?: Array<GmailCategory>;
  /**
   * Maximum messages to pull per Gmail category.
   */
  max_results?: number | null;
};

export type GmailSyncResponse = {
  pulled: number;
  messages: Array<GmailMessageRead>;
};

export type GmailWatchRequest = {
  /**
   * Google OAuth access token with Gmail read-only access.
   */
  access_token: string;
  categories?: Array<GmailCategory>;
  /**
   * Maximum messages to pull per Gmail category.
   */
  max_results?: number | null;
  /**
   * Google Cloud Pub/Sub topic, e.g. projects/my-project/topics/gmail.
   */
  topic_name?: string | null;
};

export type GmailWatchResponse = {
  email_address: string;
  history_id: string;
  expiration?: string | null;
  categories: Array<GmailCategory>;
};

export type GmailWebhookMessage = {
  data: string;
  messageId?: string | null;
  publishTime?: string | null;
};

export type GmailWebhookPayload = {
  message: GmailWebhookMessage;
  subscription?: string | null;
};

export type GmailWebhookResponse = {
  processed: boolean;
  email_address?: string | null;
  pulled?: number;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type ItemCreate = {
  name: string;
  description?: string | null;
  quantity?: number | null;
};

export type ItemRead = {
  name: string;
  description?: string | null;
  quantity?: number | null;
  id: string;
  user_id: string;
};

export type login = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type Page_ItemRead_ = {
  items: Array<ItemRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

export type UserCreate = {
  email: string;
  password: string;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
};

export type UserRead = {
  id: string;
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_verified?: boolean;
};

export type UserUpdate = {
  password?: string | null;
  email?: string | null;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type AuthJwtLoginData = {
  body: login;
};

export type AuthJwtLoginResponse = BearerResponse;

export type AuthJwtLoginError = ErrorModel | HTTPValidationError;

export type AuthJwtLogoutResponse = unknown;

export type AuthJwtLogoutError = unknown;

export type RegisterRegisterData = {
  body: UserCreate;
};

export type RegisterRegisterResponse = UserRead;

export type RegisterRegisterError = ErrorModel | HTTPValidationError;

export type ResetForgotPasswordData = {
  body: Body_auth_reset_forgot_password;
};

export type ResetForgotPasswordResponse = unknown;

export type ResetForgotPasswordError = HTTPValidationError;

export type ResetResetPasswordData = {
  body: Body_auth_reset_reset_password;
};

export type ResetResetPasswordResponse = unknown;

export type ResetResetPasswordError = ErrorModel | HTTPValidationError;

export type VerifyRequestTokenData = {
  body: Body_auth_verify_request_token;
};

export type VerifyRequestTokenResponse = unknown;

export type VerifyRequestTokenError = HTTPValidationError;

export type VerifyVerifyData = {
  body: Body_auth_verify_verify;
};

export type VerifyVerifyResponse = UserRead;

export type VerifyVerifyError = ErrorModel | HTTPValidationError;

export type UsersCurrentUserResponse = UserRead;

export type UsersCurrentUserError = unknown;

export type UsersPatchCurrentUserData = {
  body: UserUpdate;
};

export type UsersPatchCurrentUserResponse = UserRead;

export type UsersPatchCurrentUserError =
  | ErrorModel
  | unknown
  | HTTPValidationError;

export type UsersUserData = {
  path: {
    id: string;
  };
};

export type UsersUserResponse = UserRead;

export type UsersUserError = unknown | HTTPValidationError;

export type UsersPatchUserData = {
  body: UserUpdate;
  path: {
    id: string;
  };
};

export type UsersPatchUserResponse = UserRead;

export type UsersPatchUserError = ErrorModel | unknown | HTTPValidationError;

export type UsersDeleteUserData = {
  path: {
    id: string;
  };
};

export type UsersDeleteUserResponse = void;

export type UsersDeleteUserError = unknown | HTTPValidationError;

export type ReadItemData = {
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Page size
     */
    size?: number;
  };
};

export type ReadItemResponse = Page_ItemRead_;

export type ReadItemError = HTTPValidationError;

export type CreateItemData = {
  body: ItemCreate;
};

export type CreateItemResponse = ItemRead;

export type CreateItemError = HTTPValidationError;

export type DeleteItemData = {
  path: {
    item_id: string;
  };
};

export type DeleteItemResponse = unknown;

export type DeleteItemError = HTTPValidationError;

export type SyncGmailMessagesData = {
  body: GmailSyncRequest;
};

export type SyncGmailMessagesResponse = GmailSyncResponse;

export type SyncGmailMessagesError = HTTPValidationError;

export type GetGmailConnectUrlResponse = GmailConnectUrlResponse;

export type GetGmailConnectUrlError = unknown;

export type GetGmailStatusResponse = GmailConnectionStatusResponse;

export type GetGmailStatusError = unknown;

export type GmailOauthCallbackData = {
  query: {
    code: string;
    state: string;
  };
};

export type GmailOauthCallbackResponse = unknown;

export type GmailOauthCallbackError = HTTPValidationError;

export type TriageGmailWithMcpData = {
  body: GmailMcpTriageRequest;
};

export type TriageGmailWithMcpResponse = GmailMcpTriageResponse;

export type TriageGmailWithMcpError = HTTPValidationError;

export type TriageConnectedGmailData = {
  body: ConnectedGmailTriageRequest;
};

export type TriageConnectedGmailResponse = GmailMcpTriageResponse;

export type TriageConnectedGmailError = HTTPValidationError;

export type WatchGmailMessagesData = {
  body: GmailWatchRequest;
};

export type WatchGmailMessagesResponse = GmailWatchResponse;

export type WatchGmailMessagesError = HTTPValidationError;

export type GmailWebhookData = {
  body: GmailWebhookPayload;
  query?: {
    token?: string | null;
  };
};

export type GmailWebhookResponse2 = GmailWebhookResponse;

export type GmailWebhookError = HTTPValidationError;

export type SendGmailMessageData = {
  body: GmailSendRequest;
};

export type SendGmailMessageResponse = GmailSendResponse;

export type SendGmailMessageError = HTTPValidationError;
